### ISSUE TITLE
Cant get DFU to work on MacOS

### ISSUE THREAD

**Issue by Exellent1988** [lingex/G610Rebuild#4]
HY @lingex,
first of all thank you for your awesome work! I allready flashed my G610 via ST-Link which worked awesome. But now that i modifyed the firmware ( forked it). I can't get the DFU flash to work. 
I tryed to flash it with the STM32Cube Programmer which also supports DFU. But it hangs and then timesout when trying to write the FW. ( reading is possible tough).

I saw your modded DFuSe package, but that will only work on windows. Can you tell me what you modded so that i can replicate that for a mac tool?
Or do you have any other Idea what i could try to get it to work?
Thanks in advance Exel

**Comment by lingex** [comment]
Hi @Exellent1988,
The STM32Cube Programmer may not work, because the MCU's flash is 64KB officially guaranteed by ST. We currently use it as 128KB, so the software may not support the 64KB in the tail (I haven't tried it).

The DFUse I had modified is to make it handier. You can compare the latest version with the first one using git diff or look at the commits. Anyway, not necessary. This tool is written in Visual C++, ST release for years. Sorry, I don't know if you can build it in mac. Maybe you can try some more tools.

Another solution, give up the official FW and only use the first 64KB flash(which has to change the APP address), so the STM32Cube Programmer may work.

**Comment by Exellent1988** [comment]
Hy @lingex , thanks for your response.
Could you you point me in the right directions to change the bootloader or the fw itself to override the app address?

**Comment by lingex** [comment]
@Exellent1988 
First, you have to modify the USB device interface (USBD_DFU_MEDIA)
https://github.com/lingex/STM32L_DFU_Solution this repo has two branches, with a little difference. The master branch is what you need, and the only thing you need to do is to build and flash it if I recall it correctly.

Second, the main.h:163  (APP_ADDR) defines the APP address.
